services:
  - type: web
    name: flask-html-to-pdf
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y wkhtmltopdf
    startCommand: gunicorn app:app
    plan: free